---
- name: Generate Airside RCx Generator Config
  ansible.builtin.template:
    src: airside_rcx_generator_config.j2
    dest: "{{ host_configs_dir }}/airside_rcx_generator_config.json"

- name: Install Generator Scripts
  ansible.builtin.shell:
    cmd: "{{ ansible_python_interpreter }} {{ ansible_env.HOME }}/config_generators/setup.py install"
    chdir: "{{ ansible_env.HOME }}/config_generators"

- name: Copy JSON Sources
  ansible.posix.synchronize:
    src: "{{ airside_rcx_generator.json.source_path }}"
    dest: "{{ host_configs_dir }}"
  when: airside_rcx_generator.data_source == 'json'

- name: Run Airside RCx Generator from JSON
  ansible.builtin.shell:
    cmd: "{{ venv_for_ansible }}/bin/config-gen-json.airsidercx {{ host_configs_dir }}/airside_rcx_generator_config.json"
    chdir: "{{ ansible_env.HOME }}/config_generators/src/volttron/haystack/parser/airsidercx/"
  register: generator_return_json
  failed_when: generator_return_json.rc < 0 or generator_return_json.rc > 1
  when: airside_rcx_generator.data_source == 'json'

- name: Report Generator Errors from JSON
  ansible.builtin.copy:
    dest: airside_rcx_issues.json
    content: "{{ generator_return_json.stderr }}"
  when: generator_return_json.rc | default('') == 1

- name: Run Airside RCx Generator from Database
  ansible.builtin.shell:
    cmd: "{{ ansible_python_interpreter }} config_intellimation.py {{ host_configs_dir }}/airside_rcx_generator_config.json"
    chdir: "{{ ansible_env.HOME }}/config_generators/src/volttron/haystack/parser/airsidercx/intellimation"
  register: generator_return_db
  failed_when: generator_return_db.rc < 0 or generator_return_db.rc > 1
  when: airside_rcx_generator.data_source == 'db'

- name: Report Generator Errors from Database
  ansible.builtin.copy:
    dest: airside_rcx_issues.json
    content: "{{ generator_return_db.stderr }}"
  when: generator_return_db.rc | default('') == 1

- name: Fetch Generator Error Report
  ansible.builtin.fetch:
    dest: "{{ generator_reports_dir }}/{{ inventory_hostname }}/airside_rcx_issues.json"
    src: "{{ host_configs_dir }}/airside_rcx/unmapped_device_details" # airside_rcx_issues.json
    flat: yes
  when: (generator_return_json.rc is defined and generator_return_json.rc == 1) or (generator_return_db.rc is defined and generator_return_db.rc == 1)

- name: Find Generated Files
  ansible.builtin.find:
    paths: "{{ host_configs_dir }}/airside_rcx"
    excludes: "unmapped_device_details"
  register: airside_rcx_configs

- name: Load VOLTTRON Airside RCx Configurations
  ansible.builtin.slurp:
    src: "{{ item.path }}"
  register: airside_rcx_config_set
  loop: "{{ airside_rcx_configs.files }}"

- name: Install Config Set
  include_tasks: setup_agents.yml
  loop: "{{ airside_rcx_config_set.results | map(attribute='content') | map('b64decode') | map('from_json') }}"
